/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    extern "C" {
        pub fn execute(
            a: ::std::os::raw::c_uint,
            b: ::std::os::raw::c_uint,
            securityParameter: ::std::os::raw::c_uint,
        );
    }
}
